---
root: true
env:
  browser: true
  commonjs: true
  es2020: true
  node: true
  shared-node-browser: true
extends:
  - plugin:jsx-a11y/recommended
  - plugin:ramda/recommended
  - plugin:react-hooks/recommended
  - standard-jsx
  - standard-with-typescript
  - prettier
globals:
  __DEV__: false
  __SSR__: false
ignorePatterns:
  - '**/vendor/'
  - '**/node_modules/'
  - 'build/**'
overrides:
  - files: config/**/*.js
    rules:
      indent:
        - error
        - 2
        - MemberExpression: 'off'
      sort-keys: 'off'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
    globalReturn: false
  ecmaVersion: 2020
  project: ./tsconfig.json
  sourceType: module
plugins:
  - prettier
  - ramda
  - react
  - react-hooks
  - '@typescript-eslint'
settings:
  react:
    linkComponents:
      - linkAttribute: to
        name: Link
    version: detect
rules:
  '@typescript-eslint/naming-convention':
    - error
    - custom:
        match: false
        regex: '^I[A-Z]'
      format: [PascalCase]
      selector: interface

  prettier/prettier:
    - error
    - usePrettierrc: true

  react/sort-comp:
    - error
    - order:
        - static-variables
        - static-methods
        - instance-variables
        - instance-methods
        - everything-else
        - render
