env:
  browser: true
  commonjs: true
  es2020: true
  node: true
  shared-node-browser: true
globals:
  __DEV__: readonly
  Hyphenopoly: readonly
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    globalReturn: false
    jsx: true
  ecmaVersion: 2020
  sourceType: module
extends:
  - 'eslint:recommended'
  - 'plugin:jsx-a11y/recommended'
  - 'plugin:ramda/recommended'
  - 'plugin:react-hooks/recommended'
  - 'plugin:react/recommended'
plugins:
  - babel
  - jsx-a11y
  - ramda
  - react
  - react-hooks
  - sort-destructure-keys
root: true
settings:
  react:
    version: detect
rules:
  babel/no-unused-expressions:
    - warn
    - allowShortCircuit: true
      allowTaggedTemplates: true
      allowTernary: true
  babel/object-curly-spacing:
    - warn
    - always
    - objectsInObjects: false

  react/display-name: 'off'
  react/jsx-closing-bracket-location:
    - warn
    - after-props
  react/jsx-curly-newline:
    - warn
    - consistent
  react/jsx-curly-spacing:
    - warn
    - attributes: true
      children: true
      spacing:
        objectLiterals: never
      when: always
  react/jsx-filename-extension:
    - warn
    - allow: always
      extensions: [.js]
  react/jsx-indent:
    - warn
    - 2
    - checkAttributes: true
      indentLogicalExpressions: true
  react/jsx-indent-props:
    - warn
    - 2
  react/jsx-pascal-case:
    - error
    - allowAllCaps: true
  react/jsx-sort-default-props:
    - error
    - ignoreCase: true
  react/jsx-sort-props:
    - warn
    - callbacksLast: true
      ignoreCase: true
      reservedFirst: true
      shorthandFirst: true
  react/jsx-tag-spacing:
    - warn
    - beforeSelfClosing: never
  react/prop-types: 'off'
  react/react-in-jsx-scope: 'off'
  react/sort-comp:
    - error
    - order:
        - static-variables
        - static-methods
        - instance-variables
        - instance-methods
        - everything-else
        - render
  react/sort-prop-types:
    - error
    - callbacksLast: true
      ignoreCase: true
      requiredFirst: true
      sortShapeProp: true

  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps:
    - warn
    - additionalHooks: RecoilCallback

  sort-destructure-keys/sort-destructure-keys:
    - warn
    - caseSensitive: false

  accessor-pairs: 'off'
  comma-dangle:
    - warn
    - always-multiline
  eol-last: 'off'
  indent:
    - warn
    - 2
  no-extra-boolean-cast: 'off'
  no-extra-semi: 'off'
  no-multiple-empty-lines:
    - warn
    - max: 2
      maxBOF: 0
  no-regex-spaces: 'off'
  no-trailing-spaces: 'off'
  no-unused-expressions: 'off'
  no-unused-labels: 'off'
  no-unused-vars:
    - error
    - argsIgnorePattern: '^_'
      varsIgnorePattern: '^_'
  object-curly-spacing: 'off'
  prefer-const: warn
  prefer-rest-params: error
  radix: error
  semi:
    - warn
    - never
  sort-imports:
    - warn
    - ignoreCase: true
  sort-keys:
    - error
    - asc
    - caseSensitive: false
      natural: true
  sort-vars: 'off'
  template-curly-spacing:
    - warn
    - always
overrides:
  - files: '**/config/**'
    rules:
      indent: 'off'
      sort-keys: 'off'
      sort-vars: 'off'
