---
env:
  browser: true
  commonjs: true
  es2020: true
  node: true
  shared-node-browser: true
parser: '@babel/eslint-parser'
parserOptions:
  babelOptions:
    configFile: ./.babelrc.js
  ecmaFeatures:
    jsx: true
  sourceType: module
extends:
  - 'eslint:recommended'
  - plugin:ramda/recommended
  - plugin:react-hooks/recommended
  - plugin:react/recommended
  - standard
  - standard-jsx
  - standard-react
plugins:
  - '@babel/eslint-plugin'
  - ramda
  - react
  - react-hooks
  - sort-destructure-keys
settings:
  react:
    version: '17'
rules:
  '@babel/no-unused-expressions':
    - warn
    - allowShortCircuit: true
      allowTaggedTemplates: true
      allowTernary: true
  '@babel/semi':
    - warn
    - never

  react/display-name: 'off'
  react/jsx-closing-bracket-location:
    - warn
    - after-props
  react/jsx-curly-newline:
    - warn
    - consistent
  react/jsx-curly-spacing:
    - warn
    - children:
        when: always
      attributes:
        when: always
      when: always
      spacing:
        objectLiterals: never
  react/jsx-indent:
    - warn
    - 2
    - checkAttributes: true
      indentLogicalExpressions: true
  react/jsx-indent-props:
    - warn
    - 2
  react/jsx-pascal-case:
    - error
    - allowAllCaps: true
  react/jsx-sort-default-props:
    - error
    - ignoreCase: true
  react/jsx-sort-props:
    - warn
    - callbacksLast: true
      ignoreCase: true
      reservedFirst: true
      shorthandFirst: true
  react/jsx-tag-spacing:
    - warn
    - beforeSelfClosing: always
  react/prop-types: 'off'
  react/react-in-jsx-scope: 'off'
  react/self-closing-comp: warn
  react/sort-comp:
    - error
    - order:
        - static-variables
        - static-methods
        - instance-variables
        - instance-methods
        - everything-else
        - render
  react/sort-prop-types:
    - error
    - callbacksLast: true
      ignoreCase: true
      requiredFirst: true
      sortShapeProp: true

  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps:
    - warn
    - additionalHooks: RecoilCallback

  sort-destructure-keys/sort-destructure-keys:
    - warn
    - caseSensitive: false

  arrow-parens:
    - warn
    - as-needed
  comma-dangle:
    - warn
    - always-multiline
  eol-last: 'off'
  indent:
    - warn
    - 2
  no-extra-semi: warn
  no-multiple-empty-lines:
    - warn
    - max: 2
      maxBOF: 0
  no-trailing-spaces: 'off'
  no-unused-expressions: 'off'
  no-unused-vars:
    - error
    - argsIgnorePattern: '^_\w+'
      varsIgnorePattern: '^_\w+'
  no-var: warn
  object-curly-spacing:
    - warn
    - always
    - objectsInObjects: false
  prefer-const: warn
  prefer-rest-params: error
  radix: error
  semi: 'off'
  sort-imports:
    - warn
    - ignoreCase: true
  sort-keys:
    - error
    - asc
    - caseSensitive: false
      natural: true
  sort-vars: warn
  template-curly-spacing:
    - warn
    - always
overrides:
  - files: '**/config/**'
    rules:
      indent: 'off'
      sort-keys: 'off'
      sort-vars: 'off'
