---
env:
  browser: true
  commonjs: true
  es2020: true
  node: true
  shared-node-browser: true
extends:
  - standard-with-typescript
  - standard-jsx
  - prettier
  - plugin:prettier/recommended
  - prettier-standard/prettier-file
  - plugin:jsx-a11y/recommended
  - plugin:react-hooks/recommended
globals:
  __DEV__: false
  __SSR__: false
ignorePatterns:
  - '**/vendor/'
  - '**/node_modules/'
  - 'build/**'
overrides:
  - files: config/**/*.js
    rules:
      indent:
        - error
        - 2
        - MemberExpression: 'off'
      sort-keys: 'off'
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
    globalReturn: false
  ecmaVersion: 2020
  projectFile: ./tsconfig.json
  sourceType: module
plugins:
  - ramda
  - react
  - react-hooks
  - '@typescript-eslint'
settings:
  react:
    linkComponents:
      - linkAttribute: to
        name: Link
    version: detect
rules:
  arrow-parens:
    - error
    - as-needed
    - requireForBlockBody: false
  comma-dangle:
    - error
    - arrays: always-multiline
      exports: always-multiline
      functions: always-multiline
      imports: always-multiline
      objects: always-multiline

  camelcase: 'off'
  babel/camelcase:
    - error
    - ignoreDestructuring: false
      properties: always

  eol-last: 'off'
  indent:
    - error
    - 2
  jsx-quotes:
    - error
    - prefer-single

  new-cap: 'off'
  babel/new-cap:
    - error
    - capIsNew: false
      newIsCap: true

  no-trailing-spaces: 'off'
  no-unused-expressions: 'off'
  babel/no-unused-expressions:
    - error
    - allowShortCircuit: true
      allowTernary: true

  object-curly-spacing: 'off'
  babel/object-curly-spacing:
    - error
    - always

  quotes: 'off'
  babel/quotes:
    - error
    - single
    - allowTemplateLiterals: true
      avoidEscape: true

  semi: 'off'
  babel/semi:
    - error
    - never

  sort-imports:
    - error
    - ignoreCase: true
  sort-keys:
    - error
    - asc
    - caseSensitive: false
      natural: true
  template-curly-spacing:
    - error
    - always

  react/jsx-closing-bracket-location:
    - error
    - nonEmpty: after-props
      selfClosing: after-props
  react/jsx-curly-newline: 'off'
  react/jsx-curly-spacing:
    - error
    - attributes: true
      children: true
      spacing:
        objectLiterals: never
      when: always
  react/jsx-indent:
    - error
    - 2
    - checkAttributes: true
      indentLogicalExpressions: true
  react/jsx-indent-props:
    - error
    - 2
  react/prop-types: 'off'
  react/sort-comp:
    - error
    - order:
        - static-variables
        - static-methods
        - instance-variables
        - instance-methods
        - everything-else
        - render
