---
env:
    browser: true
    commonjs: true
    es6: true
    node: true
    shared-node-browser: true
extends:
    - eslint:recommended
    - plugin:ramda/recommended
    - plugin:react/recommended
    - standard
    - standard-jsx
    - standard-react
globals:
    __DEV__: false
    __SSR__: false
    React: false
    ReactDOM: false
ignorePatterns:
    - '**/vendor/'
    - '**/node_modules/'
    - 'build/**'
parser: babel-eslint
parserOptions:
    babelOptions:
        configFile: ./.babelrc.js
    ecmaFeatures:
        jsx: true
        globalReturn: false
plugins:
    - babel
    - ramda
    - react
    - react-hooks
settings:
    react:
        linkComponents:
            - linkAttribute: to
              name: Link
        version: detect
rules:
    arrow-parens:
        - error
        - as-needed
        - requireForBlockBody: false
    comma-dangle:
        - error
        - arrays: always-multiline
          exports: always-multiline
          functions: always-multiline
          imports: always-multiline
          objects: always-multiline

    camelcase: 'off'
    babel/camelcase:
        - error
        - ignoreDestructuring: false
          properties: always

    eol-last: 'off'
    indent:
        - error
        - 4
    jsx-quotes:
        - error
        - prefer-single

    new-cap: 'off'
    babel/new-cap:
        - error
        - capIsNew: false
          newIsCap: true

    no-trailing-spaces: 'off'
    no-unused-expressions: 'off'
    babel/no-unused-expressions:
        - error
        - allowShortCircuit: true
          allowTernary: true

    object-curly-spacing: 'off'
    babel/object-curly-spacing:
        - error
        - always

    quotes: 'off'
    babel/quotes:
        - error
        - single
        - allowTemplateLiterals: true
          avoidEscape: true

    semi: 'off'
    babel/semi:
        - error
        - never

    sort-imports:
        - error
        - ignoreCase: true
    sort-keys:
        - error
        - asc
        - caseSensitive: false
          natural: true
    template-curly-spacing:
        - error
        - always

    react/jsx-closing-bracket-location:
        - error
        - nonEmpty: after-props
          selfClosing: after-props
    react/jsx-curly-newline:
        - error
        - multiline: require
          singleline: forbid
    react/jsx-curly-spacing:
        - error
        - attributes: true
          children: true
          spacing:
              objectLiterals: never
          when: always
    react/jsx-indent:
        - error
        - 4
        - checkAttributes: true
          indentLogicalExpressions: true
    react/jsx-indent-props:
        - error
        - 4
    react/prop-types: 'off'
    react/sort-comp:
        - error
        - order:
              - static-variables
              - static-methods
              - instance-variables
              - instance-methods
              - everything-else
              - render
