extends:
  - stylelint-config-recommended
  - stylelint-config-standard
  - stylelint-config-styled-components
plugins:
  - stylelint-order
  - stylelint-config-rational-order/plugin
  - stylelint-no-unsupported-browser-features
ignoreFiles:
  - 'node_modules/**/*'
  - 'dist/**/*'
  - '**/*.d.ts'
rules:
  order/properties-order:
    - []
    - unspecified: bottom
      emptyLineMinimumPropertyThreshold: 4

  plugin/no-unsupported-browser-features:
    - true
    - browsers: ['last 2 major versions and >1% in US and not dead and not IE > 0']

  plugin/rational-order:
    - true
    - empty-line-between-groups: threshold
      empty-lines-within-groups: false

  block-no-empty: null
  color-hex-case: upper
  declaration-empty-line-before: null
  font-family-no-missing-generic-family-keyword: null
  indentation: 4
  no-eol-whitespace: null
  no-missing-end-of-source-newline: null
  value-keyword-case: null
