extends:
  - stylelint-config-recommended
  - stylelint-config-standard
  - stylelint-config-styled-components
plugins:
  - stylelint-order
rules:
  order/properties-alphabetical-order: true
  color-hex-case: upper
  declaration-empty-line-before: null
  font-family-no-missing-generic-family-keyword: null
  indentation: 2
  no-eol-whitespace: null
