nodeLinker: node-modules
npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmAuthToken: '${FONT_AWESOME_NPM_TOKEN:-}'
    npmRegistryServer: https://npm.fontawesome.com
  gsap:
    npmAlwaysAuth: true
    npmAuthToken: '${GSAP_NPM_TOKEN:-}'
    npmRegistryServer: https://npm.greensock.com
yarnPath: .yarn/releases/yarn-2.4.0.cjs
