version: '3.8'

services:
  app:
    build:
      args:
        - FONT_AWESOME_NPM_TOKEN
        - GSAP_NPM_TOKEN
      context: .
    command:
      - /bin/sh
      - -c
      - yarn && yarn vite
    environment:
      - VIRTUAL_HOST=menagerie.here
    expose:
      - "3000"
    networks:
      - default
      - nginx-proxy
    volumes:
      - type: bind
        source: .
        target: /app
      - type: volume
        source: node_modules
        target: /app/node_modules
      - type: volume
        source: dot_yarn
        target: /app/.yarn


volumes:
  node_modules:
  dot_yarn:

networks:
  default:
  nginx-proxy:
    external: true
    name: nginx-proxy
