version: '3.8'

services:
  app:
    build:
      context: .
    environment:
      - VIRTUAL_HOST=menagerie.here
    expose:
      - "9090"
    networks:
      - default
      - nginx-proxy
    volumes:
      - type: bind
        source: .
        target: /app
      - type: volume
        source: node_modules
        target: /app/node_modules
        volume:
          nocopy: true
      - type: volume
        source: dot_yarn
        target: /app/.yarn
      - type: volume
        source: yarn_cache
        target: /var/cache/yarn
    secrets:
      - npm_credentials

volumes:
  node_modules:
  dot_yarn:
  yarn_cache:

networks:
  default:
  nginx-proxy:
    external: true
    name: nginx-proxy

secrets:
  npm_credentials:
    file: .env
